#include "../game/atto_core.h"
#include "../sim/atto_sim_map.h"

namespace atto {
    REFLECT_STRUCT_BEGIN( GameSettings )
        REFLECT_STRUCT_MEMBER( windowWidth )
        REFLECT_STRUCT_MEMBER( windowHeight )
        REFLECT_STRUCT_MEMBER( windowStartPosX )
        REFLECT_STRUCT_MEMBER( windowStartPosY )
        REFLECT_STRUCT_MEMBER( noAudio )
        REFLECT_STRUCT_MEMBER( fullscreen )
        REFLECT_STRUCT_MEMBER( vsync )
        REFLECT_STRUCT_MEMBER( showDebug )
        REFLECT_STRUCT_MEMBER( usePackedAssets )
        REFLECT_STRUCT_MEMBER( basePath )
        REFLECT_STRUCT_MEMBER( masterVolume )
        REFLECT_STRUCT_MEMBER( serverIp )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( TextureResource )
        REFLECT_STRUCT_MEMBER( name )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( AudioResource )
        REFLECT_STRUCT_MEMBER( name )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( SpriteActuation )
        REFLECT_STRUCT_MEMBER( frameIndex )
        REFLECT_STRUCT_MEMBER( audioGroup )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( SpriteResourceCreateInfo )
        REFLECT_STRUCT_MEMBER( frameCount )
        REFLECT_STRUCT_MEMBER( frameXCount )
        REFLECT_STRUCT_MEMBER( frameYCount )
        REFLECT_STRUCT_MEMBER( frameWidth )
        REFLECT_STRUCT_MEMBER( frameHeight )
        REFLECT_STRUCT_MEMBER( frameRate )
        REFLECT_STRUCT_MEMBER( bakeInAtlas )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( SpriteResource )
        REFLECT_STRUCT_MEMBER( textureResource )
        REFLECT_STRUCT_MEMBER( createInfo )
        REFLECT_STRUCT_MEMBER( frameActuations )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( AudioGroupResource )
        REFLECT_STRUCT_MEMBER( maxInstances )
        REFLECT_STRUCT_MEMBER( minTimeToPassForAnotherSubmission )
        REFLECT_STRUCT_MEMBER( stealMode )
        REFLECT_STRUCT_MEMBER( sounds )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( PlayerMonies )
        REFLECT_STRUCT_MEMBER( power )
        REFLECT_STRUCT_MEMBER( cash )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( Structure )
        REFLECT_STRUCT_MEMBER( buildCost )
        REFLECT_STRUCT_MEMBER( buildTimeSeconds )
        REFLECT_STRUCT_END()

        REFLECT_STRUCT_BEGIN( SimEntity )
        REFLECT_STRUCT_MEMBER( type )
        REFLECT_STRUCT_MEMBER( movable )
        REFLECT_STRUCT_MEMBER( collider )
        REFLECT_STRUCT_MEMBER( structure )
        REFLECT_STRUCT_MEMBER( spriteSelectionOffset )
        REFLECT_STRUCT_MEMBER( sndOnSelect )
        REFLECT_STRUCT_MEMBER( sndOnMove )
        REFLECT_STRUCT_MEMBER( sndOnAttack )
        REFLECT_STRUCT_MEMBER( sndOnShoot )
        REFLECT_STRUCT_MEMBER( sprIdleSide )
        REFLECT_STRUCT_MEMBER( sprIdleDown )
        REFLECT_STRUCT_MEMBER( sprIdleUp )
        REFLECT_STRUCT_MEMBER( sprWalkSide )
        REFLECT_STRUCT_MEMBER( sprWalkDown )
        REFLECT_STRUCT_MEMBER( sprWalkUp )
        REFLECT_STRUCT_MEMBER( sprAttackSide )
        REFLECT_STRUCT_MEMBER( sprAttackDown )
        REFLECT_STRUCT_MEMBER( sprAttackUp )
        REFLECT_STRUCT_MEMBER( sprDeath )
        REFLECT_STRUCT_MEMBER( sprSelection )
        REFLECT_STRUCT_END()

}